### ISSUE TITLE
Clear preset stroke and fill colors of path elements

### ISSUE THREAD

**Issue by machacekmartin** [troccoli/blade-health-icons#14]
[The source package](https://github.com/resolvetosavelives/healthicons) had an issue, in which icons did not have `currentColor`, `fill`, and `stroke` set properly in order to easily manipulate their colors, instead, icons usually had `fill` of #333333 directly on `path` elements

[One of their PRs fixed it](https://github.com/resolvetosavelives/healthicons/issues/156#issuecomment-1572690836), the maintainers added a command (`remove-svg-backgrounds`) which should go through the svgs and update these attributes properly. 
I suspect your package does not use the command, since no .svg in the source folder has any `currentColor` attribute and still uses `fill` and `stroke` attributes on path elements (I may have overlooked something, but I haven't found any other solution).

Please, could you make sure this package includes correct .svgs after they go through their command?

**Comment by troccoli** [comment]
Hi @machacekmartin ,

Thank you for reporting it. I'm away at the moment so I will look at it in a couple of weeks.

It was actually me who initially filed the original issue with them. At the time they weren't working on it so I implemented my own solution.

I suspect that, in the latest release of my package, I forgot to remove my workaround.

Once again, thanks for reporting it.

Giulio

**Comment by machacekmartin** [comment]
@troccoli Happy to hear that! Please tag this when the fix is released :)

**Comment by machacekmartin** [comment]
Any updates on this?

**Comment by troccoli** [comment]
Hi @machacekmartin 

I had a look and it turned out I don't do anything with the actaul SVG. I could have fixed it myself as I did before but I didn't want to, as the goal, now that they release the icons in its own package, is to just use whatever they release and however they release them.

After a big of digging, I found oout that they have just release a new version of the package, 1.0.1. You can find more information [here](https://github.com/resolvetosavelives/healthicons/issues/195).

So, I have released verison 3.0.1 of my package that should resolve your issue.

Thank you for reporting it.

Giulio

**Comment by machacekmartin** [comment]
@troccoli Amazing, thank youuu!
